commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/',CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>',CommentDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

from articleapp.models import Article


# Create your models here.
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL,null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,null=True, related_name='comment')

    content = models.TextField(null=False)

    create_at = models.DateTimeField(auto_now=True)

commentapp/forms.py
from django.forms import ModelForm

from commentapp.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields=['content']

commentapp/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView
from django.urls import reverse

from articleapp.models import Article
from commentapp.decorator import comment_ownership_required
from commentapp.forms import CommentCreationForm
from commentapp.models import Comment


# Create your views here.

class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.article.pk})


@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'
    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.article.pk})

commentapp/templates/commentapp/create.html
{% load django_bootstrap5 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Comment Create</h4>
    </div>
    <form action="{% url 'commentapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
      <input type="hidden" name="article_pk" value="{{article.pk}}">
    </form>
  </div>

{% endblock %}

commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div style = "text-align : center; max-width : 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Delete Comment : {{target_comment.content}}</h4>
        </div>
        <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method = "post">
            {% csrf_token %}
            <input type="submit" class = "btn btn-danger rounded-pill col-6 mt-3 ">
        </form>
    </div>

{% endblock %}

commentapp/templates/commentapp/detail.html
<div style="border: 1px solid; text-align:left; padding: 4%; margin: 1rem 0; border-radius: 1rem;
border-color:#bbb;" >
  <div>
    <strong>
      {{ comment.writer.profile.nickname }}
    </strong>
    &nbsp&nbsp&nbsp
    {{ comment.create_at }}
  </div>
  <div style="margin: 1rem 0;">
    {{comment.content}}
  </div>

  {% if comment.writer == user %}
  <div style="text-align: right">
    <a href="{% url 'commentapp:delete' pk=comment.pk %}" \\
       class="btn btn-danger rounded-pill">
      Delete
    </a>
  </div>
  {% endif %}
</div>